#!/usr/bin/env node
import {exec} from './script-helpers.js'

try {
  const branch = exec(`git rev-parse --abbrev-ref HEAD`).trim()
  const remoteRepo = exec(`git config branch.${branch}.remote`).trim()
  const remoteBranchFullName = exec(`git rev-parse --abbrev-ref --symbolic-full-name ${branch}@{u}`).trim()
  const remoteBranch = remoteBranchFullName.split('/').slice(1).join('/') // also deal with `feature/foo`

  const latestTag = exec('git for-each-ref refs/tags/ --count=1 --sort=-creatordate --format="%(refname:short)"').trim()

  exec(`git push ${remoteRepo} ${branch}:${remoteBranch}`)
  exec(`git push ${remoteRepo} ${latestTag}`)

  console.log(`pushed ${branch} to ${remoteBranch} on ${remoteRepo} and tag ${latestTag}`)
} catch (error) {
  console.error('Failed to push changes:', error)
  process.exit(1)
}
